apiVersion: v1
kind: ServiceAccount # тип сервиса
metadata:
  name: s3-sa-ivanazhnov # Название сервисного аккаунта
  namespace: r-mlops-k8s-9-1-3-35446443 # Namespace секрета; должен совпадать с namespace InferenceService и Secret.
secrets:
- name: s3-secret-ivanazhnov # Название секрета, к которому получен доступ